apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci
  namespace: ci

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ci-cluster-admin
subjects:
  - kind: ServiceAccount
    name: ci
    namespace: ci
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
